nav:
    Home: /
    About: /about/
    Writing: /archives/
    Projects: https://github.com/ES-Community/hexo-blog

projects_url: https://github.com/ES-Community/hexo-blog

customize:
    logo:
        enabled: true
        width: 50
        height: 50
        url: /images/logo.png
        favicon: /images/favicon.png # path to favicon
    social_links:
        github: https://github.com/ES-Community
        # twitter: /
        # facebook: /
        # linkedin: /
    post_count: 10
    highlight: monokai-sublime

# RSS
rss: 

# Plugins
plugins:
    disqus_shortname: # Disqus Comments Shortname
    google_analytics: UA-86660611-1 # enter the tracking ID for your Google Analytics

# Miscellaneous
miscellaneous:
    open_graph: # see http://ogp.me
        fb_app_id:
        fb_admins:
        twitter_id:
        google_plus:
